kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: maven:3-jdk-10
  commands:
    - echo "Compiling the code..."
    - mvn clean package

- name: test
  image: maven:3-jdk-10
  commands:
    - echo "Running tests"
    - java -cp target/helloworld-1.1.jar com.coveros.demo.helloworld.HelloWorld

- name: deploy
  image: drone/drone:latest
  settings:
    kubernetes_server: https://kubernetes.default
    kubernetes_certificate: $CERTIFICATE
    kubernetes_token: $TOKEN
  commands:
    - kubectl apply -f deployment.yaml

- name: deploy-runner
  image: drone/drone-runner-kube:latest
  settings:
    kubernetes_server: https://kubernetes.default
    kubernetes_certificate: $CERTIFICATE
    kubernetes_token: $TOKEN
  commands:
    - kubectl apply -f runner-deployment.yaml
